extends Node

var tutorials : Dictionary[String, Tutorial] = {
	"BeginningTutorial0" : Tutorial.new("BeginningTutorial0","Grandpa's Notes","To my grandson, One day you may find yourself strapped for cash. It's a bird-eat-bird world out there, so I leave you the secrets to my fishing techniques.","res://game/sprites/tutorials/tutorial0.png"),
	"BeginningTutorial1" : Tutorial.new("BeginningTutorial1","How to Fish","Of course, fishing starts how you normally would. Cast your fishing line to where fish are and they'll slowly approach your fishing hook.","res://game/sprites/tutorials/tutorial1.png"),
	"BeginningTutorial2" : Tutorial.new("BeginningTutorial2","How to Fish (2)","Once they get really close, surprise them with a sudden but smooth pull to send them right out of the water! Forget that 'wait until they take a bite' nonsense.","res://game/sprites/tutorials/tutorial2.png"),
	"BeginningTutorial3" : Tutorial.new("BeginningTutorial3","How to Shoot","Now that they're in the air, it's time to use that other thing I left you. Point at the fish and press the trigger. Repeat that and they'll drop dead in no time.","res://game/sprites/tutorials/tutorial3.png"),
	"BeginningTutorial4" : Tutorial.new("BeginningTutorial4","How to Shoot (2)","Of course, you gotta practice some control. After all, ammunition ain't exactly easy to come across nowadays. You can use what I've left for you to reload, but you gotta find a supplier at some point.","res://game/sprites/tutorials/tutorial4.png"),
	"BeginningTutorial5" : Tutorial.new("BeginningTutorial5","How to Pay your Taxes","Fishing can be quite a rewarding occupation, although remember that at the end your hull, the government will take a portion of your catch as taxes. It's unfortunate, but unless you're extremely behind on paying them, you don't have to worry about it.","res://game/sprites/tutorials/tutorial6.png"),
	"BeginningTutorial6" : Tutorial.new("BeginningTutorial6","Grandpa's Notes End","I hope you will make use of this final gift from me, as I wish you the best in your path as a fisherbird. As for me, I've moved on to the Tropical Isles to live out the rest of my days, please visit when you have the chance.","res://game/sprites/tutorials/tutorial5.png"),
	
	"ShoppingTutorial0" : Tutorial.new("ShoppingTutorial0","The Shop","Welcome to our humble general store. We sell a decent selection of goods, and we'll rotate products every day!","res://game/sprites/tutorials/shop0.png"),
	"ShoppingTutorial1" : Tutorial.new("ShoppingTutorial1","The Shop (2)","There are two sections in the shop: The main storefront which has items and fishing gear, and the blacksmith portion, where I can hook you up with ammo and even additional weapons.","res://game/sprites/tutorials/shop1.png"),
	"ShoppingTutorial2" : Tutorial.new("ShoppingTutorial2","The Storefront","Of course none of this comes cheap, although with how the market is nowadays, the prices for items will flucuate randomly every day. Two of the same item may even cost you differently, economics are weird like that.","res://game/sprites/tutorials/shop2.png"),
	"ShoppingTutorial3" : Tutorial.new("ShoppingTutorial3","The Storefront (2)","You can also buy some bait or a better fishing rod, which will help you out in catching more fish. Those prices are static no matter what.","res://game/sprites/tutorials/shop3.png"),
	"ShoppingTutorial4" : Tutorial.new("ShoppingTutorial4","The Blacksmith","Speaking of which, a single weapon ain't gonna help you much, especially if you run out of ammo, so it'll help to bring a secondary weapon with you. That way, you can at least bring more ammo.","res://game/sprites/tutorials/shop4.png"),
	"ShoppingTutorial5" : Tutorial.new("ShoppingTutorial5","The Blacksmith (2)","Unfortunately, each weapon's got their separate ammo caches. I forge everything by hand, so no two pistols are alike, that also goes for its ammunition.","res://game/sprites/tutorials/shop4.png"),
	"ShoppingTutorial6" : Tutorial.new("ShoppingTutorial6","The Shop End","That's it for my little introduction, so let's hope our partnership becomes a profitable one, hmm?","res://game/sprites/tutorials/shop5.png"),
}	

var tutorial_beginning : Array[String] = ["BeginningTutorial0","BeginningTutorial1","BeginningTutorial2","BeginningTutorial3","BeginningTutorial4","BeginningTutorial5","BeginningTutorial6"]
var tutorial_shopping : Array[String] = ["ShoppingTutorial0","ShoppingTutorial1","ShoppingTutorial2","ShoppingTutorial3","ShoppingTutorial4","ShoppingTutorial5","ShoppingTutorial6"]
